### PR TITLE
Inject main firebase app

### PR DESCRIPTION
**Pull request by rolandszpond**
This would allow for multiple buckets

`var storage = this.$fireApp.storage("gs://my-custom-bucket")`

### CODE REVIEW

**Comment by lupas** [comment]
@rolandszpond 
Thanks for the PR - I appreciate it!

We'll be injecting the firebase module with the coming restructuring in v7.0 (see PR https://github.com/nuxt-community/firebase-module/pull/258) as $fireModule anyway, so I won't be merging this since the code is already written in the PR that is in testing phase.

Now with the current version 6, wouldn't `this.$fireStorageObj("gs://my-custom-bucket")` work for your purposes?

**Comment by rolandszpond** [comment]
@lupas It wasn't working before when I tried that. I've upgraded to v7 and tried both `this.$fire.storage('gs://my-custom-bucket)` and `this.$fireModule.storage('gs://my-custom-bucket')` and I get the following errors:

while using `this.$fire.storage('gs://my-custom-bucket')`

> this.$fire.storage is not a function

while using `this.$fireModule.storage('gs://my-custom-bucket')`

> Firebase: firebase.storage() takes either no argument or a Firebase App instance. (app/invalid-app-argument).

**Comment by rolandszpond** [comment]
@lupas Figured it out using:
`this.$fireModule.app().storage('gs://my-custom-bucket')`

**Comment by lupas** [comment]
Hey @rolandszpond 

Great to hear and thanks again for the PR anyway! 

I'll keep in my head (resp. in issue https://github.com/nuxt-community/firebase-module/issues/261) to someday implement an easy way to create multiple buckets as a built-in feature.

**Pull request closed without merging**
