### PR TITLE
docs: migrate docs to Nuxt Content

### PR DESCRIPTION
**Pull request by ThomOrlo**
@debs-obrien This is the docs from VuePress to @nuxt/content.

- [x] Content
- [x] icon.png / logo-dark.svg / logo-light.svg / preview-dark.png / preview.png
- [x] netlify.toml file ? (https://github.com/nuxt-community/module-template/issues/60)
- [x] nuxt-ackee dependency and configuration ?

Primary color : #FFA000 (https://firebase.google.com/brand-guidelines#colors)

### CODE REVIEW

**Comment by debs-obrien** [comment]
Nice. looks great. Let me know if you are stuck on anything

**Comment by ThomOrlo** [comment]
Icons and images are missing but I don't know who can do them, maybe @Atinux ?

- docs/static/icon.png
- docs/static/logo-dark.svg
- docs/static/logo-light.svg
- docs/static/preview-dark.png
- docs/static/preview.png

**Comment by Atinux** [comment]
Sure thing :)

**Comment by lupas** [comment]
Thanks @ThomOrlo for your effort, that already looks great. 🥳
Let me know if there's any question regarding the docs and feel free to restructure, it grew a bit messy over time.

**Comment by Atinux** [comment]
Sorry for the delay, it's ready 👍 

Nice work @ThomOrlo and @lupas 👏 

Screenshot 2020-09-24 at 13 30 51

**Comment by lupas** [comment]
@Atinux Thanks a lot for your effort, that looks great!

@ThomOrlo I'll finish up the rest later today or tomorrow so we can merge this asap, I'm working on v7 and plan to already implement the new v7 documentation changes in the new docs. Thanks a lot for this PR!

**Comment by lupas** [comment]
Fixed some broken links and reorganized some content, but it already looked super nice to me so I merged it. Thanks @ThomOrlo for the PR!

@debs-obrien: I don't have Netlify access for the Nuxt Org so I can't really debug, could you check what's wrong with the deployment and let me know what to change? Did I mess up in the .toml file?

And while you're at it could you let me know if it is set to deploy from "dev" or "master" branch? 🙈 
Thanks! :)

**Comment by debs-obrien** [comment]
hi @lupas sorry was unavailable the last few days. I believe the site is now deployed. Do you still have issues with it. If so can you please ask Seb as I don't think I have access either. thanks

**Comment by lupas** [comment]
@debs-obrien 
All good now, Seb fixed it and it works like a charm. Thanks a lot!
(btw: the content docs theme really needs an algolia plugin ;))

**Comment by debs-obrien** [comment]
cool @lupas - 

you will have to submit an issue on content for that I am afraid or perhaps even a pr 🤷‍♀️

**Comment by lupas** [comment]
@debs-obrien 
There's already an issue & the PR is on my ToDo list (if no one beats me to it) 😎

**Pull request merged**
