### PR TITLE
Feat/messaging (incomplete)

### PR DESCRIPTION
**Pull request by mentAl-maZe**
This is a partial implementation of #165 after the changes done in #174 
We still need to figure out how to implement `notificationTemplate`

### CODE REVIEW

**Comment by MSkred** [comment]
Ok if you need help @ me

**Comment by mentAl-maZe** [comment]
Hi @MSkred,
thanks for joining.
Could you explain what you wanted to do with the NotificationTemplate?
What values should be possible?
Can it be a simple mapping?
e.g.
```js
{
  // [optionName]: 'propertyName'
  title: 'title',
  body: 'body',
  icon: 'image'
}
```
Or do you need static value fallbacks?

**Comment by lupas** [comment]
@MSkred @mentAl-maZe 
Okay I had a look at the issue and I think this PR should cover two things:

### 1. The **notificationKey** issue

- [X] Add a configuration option to change the key
- [ ] New `data` by default, not `notification`. "Notification" seems to lead to [issues](https://stackoverflow.com/questions/40462414/firebase-cloud-messaging-setbackgroundmessagehandler-not-called) in the messaging web client
- [ ] Rename it to `dataKey`

### 2. The Template
The payload of the notification should define the [options](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification) of notification. We should not constrain how that options object has to look like.

In my opinion, we should do the following:

- [ ] Expect the message payload to look like so:
```js
"payload": {
    "data": {
        "title": "string",
        "options": anyOptionsObject
   }
}
```

And then all we do is:
```js
  self.registration.showNotification(
    payload.title,
    payload.options
  )
```

This way we leave all the flexibility of how the notification looks to the one sending it, and we don't overcomplicate our code.

Of course we can put an example of a notification payload in our docs.

What do you guys think?

**Comment by MSkred** [comment]
Hi guys sorry for the delay. It's exactly this we need. In my case I've an entirely different payload from the backend. Then I should be able to send the full payload : `input key` and `Object`. 

> New data by default, not notification. "Notification" seems to lead to issues in the messaging web client

@lupas I use a lot the notifications in my projects and yes when the app is in the background some notifications are not received.

**Comment by MSkred** [comment]
Should I do something ? @lupas

**Comment by mentAl-maZe** [comment]
No, @lupas left it up to me to finish up the pull request, and i have not had time to finish it.
I'm sorry...
i'll finish it up in the next few days (probably on wednesday)

**Comment by lupas** [comment]
@mentAl-maZe  @MSkred 
Sorry guys, super absorbed with work and some personal stuff lately. Didn't mean to leave it up to you @mentAl-maZe ;-) I was actually thinking about finishing it up, but just got stuck in other things.

I'll make sure to work in it as soon as I find some extra time.

**Comment by mentAl-maZe** [comment]
@mentAl-maZe No worries, it's the same for me at the time...
in fact didn't get to it yesterday as planned...
Some specifics concerning the message payload are still missing i'd like to get that in before you pull

**Comment by lupas** [comment]
Replaced by https://github.com/nuxt-community/firebase-module/pull/219

**Pull request merged**
